__title__ = "paisa_core"
__description__ = "The unofficial Python client for the 5paisa trading API"
__url__ = "https://dotstar.xyz/5paisa-core"
__download_url__ = "https://github.com/kodani/paisa_core"
__version__ = "1.0.0"
__author__ = "Aniket Patel"
__author_email__ = "patelaniket165@gmail.com"
__license__ = "MIT"
